#!/bin/bash

# устанавливает вам на сервер nginx, git, vim, postgres, mysql, mongodb, PHP и так же laravel через composer

sudo apt update -y

sudo apt upgrade -y

# NGINX
sudo apt install nginx -y

# GIT
sudo apt-get install git -y

# VIM
sudo apt-get install vim -y

# POSTGRESQL
sudo apt install postgresql -y

# MYSQL
sudo apt install mysql-server -y

# MONGODB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list -y
sudo apt-get update -y
sudo apt-get install -y mongodb-org

# PHP
sudo apt install php7.3-fpm -y
sudo apt install php7.3-common php7.3-mysql php7.3-xml php7.3-xmlrpc php7.3-curl php7.3-gd php7.3-imagick php7.3-cli php7.3-dev php7.3-imap php7.3-mbstring php7.3-opcache php7.3-soap php7.3-zip php7.3-intl -y

# PHP7.3
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:ondrej/php -y
sudo apt update -y

sudo apt install php7.3-fpm php7.3-common php7.3-mysql php7.3-xml php7.3-xmlrpc php7.3-curl php7.3-gd php7.3-imagick php7.3-cli php7.3-dev php7.3-imap php7.3-mbstring php7.3-soap php7.3-zip php7.3-bcmath -y

# COMPOSER
sudo apt install composer -y
sudo apt install php-mysql php-mbstring php-tokenizer php-xml php-json php-common -y

# LARAVEL
sudo composer create-project --prefer-dist laravel/laravel laravelapp
sudo chown -R www-data:www-data laravelapp

